# -*- coding: utf-8 -*-
"""Assignment_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1haG2RBrU2xDUm5gR9DmveBWBHrBev1rD
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import warnings

warnings.filterwarnings('ignore')

"""**Task 1**"""

data = pd.read_csv('Student Data.csv')

data

data.head()

data.shape

data.describe()

plt.scatter(data['Hours Studied (X)'],data['Exam Score (y)'])
plt.xlabel('Hours Studied')
plt.ylabel('Exam Score')
plt.title("Hours studied vs Exam score")
plt.show()

x=data.iloc[:,1:2] # Selects 'Hours Studied (X)'
y = data.iloc[:,-1]

x

y

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

model = LinearRegression()

model.fit(x_train,y_train)

x_test

y_test

Predictions = model.predict(x_test)

print("Prediction :",Predictions )
print("actual :",y_test.values)

plt.scatter(data['Hours Studied (X)'],data['Exam Score (y)'])
plt.plot(x_train,model.predict(x_train),color ='red')
plt.xlabel('Hours studies')
plt.ylabel('Exam score')



predictions = model.predict(x_test)
mse = mean_squared_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

print(f"Model Accuracy (R2 Score): {r2:.4f}")
print(f"Mean Squared Error: {mse:.2f}")

print("Slope = ", model.coef_)
print("Intercept = ", model.intercept_)



"""**Task 2**"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import warnings

warnings.filterwarnings('ignore')

data = pd.read_csv('Performance.csv')

data.head()

data.info()

data.shape

data['Result']= data['Result'].map({'Pass' : 1,'Fail' : 0})

data.head()

plt.scatter(data['Study Hours'],data['Attendance (%)'],c=data['Result'])

x =data.iloc[:,1:-1]

y = data.iloc[:,-1]

x

y

x_train,x_test,y_train,y_test =train_test_split(x,y,test_size= 0.2)

x_train

y_train

model = LogisticRegression()

model.fit(x_train,y_train)

model.predict(x_test)

y_test

from sklearn.metrics import accuracy_score

prediction = model.predict(x_test)

print(accuracy_score(y_test,prediction))