# -*- coding: utf-8 -*-
"""assignment_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DDP4Xpj2rXr2Tu7RmQv-09YQIerzK1MU

# Housing Price Prediction

### 1. Imports and Data Loading
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

data = pd.read_csv('Housing.csv')
data.head()

data.shape

data.info

data.describe()

"""### 2. Data Cleaning
Checking for nulls and duplicates, then handling them.
"""

# Checking for missing values
print("Null values:\n", data.isnull().sum())

# Checking and removing duplicates
print("\nDuplicates found:", data.duplicated().sum())
data.drop_duplicates(inplace=True)

"""### 3. Preprocessing & Encoding
Converting categorical text into numerical values.
"""

# Binary encoding for yes/no columns
le = LabelEncoder()
binary_cols = ['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea']
for col in binary_cols:
    data[col] = le.fit_transform(data[col])

# One-Hot Encoding for furnishingstatus (avoiding dummy variable trap)
data = pd.get_dummies(data, columns=['furnishingstatus'], drop_first=True, dtype=int)
data.head()

plt.figure(figsize=(18,5))
sns.heatmap(data.corr(numeric_only=True), annot = True, cmap = "coolwarm")

plt.figure(figsize = (15,8))
sns.scatterplot(data=data ,x='area', y = 'price')
plt.title('relation between area and price')
plt.show()

cols_to_drop = ['hotwaterheating','basement','guestroom','furnishingstatus_unfurnished','furnishingstatus_semi-furnished']
data = data.drop(cols_to_drop, axis = 1)

data.columns

plt.figure(figsize=(18,5))
sns.heatmap(data.corr(numeric_only=True), annot = True, cmap = "coolwarm")

top_features = ['area','bathrooms','airconditioning','stories']

fig, axes = plt.subplots(2, 2,figsize=(10, 8))
axes = axes.flatten()
for i, col in enumerate(top_features):
    if data[col].dtype in ['int64','float64']:
        sns.scatterplot(x=data[col],y=data['price'],ax=axes[i])
    else:
        sns.boxplot(x=data[col],y=data['price'],ax=axes[i])
        axes[i].set_title(f'{col} vs Price')
        axes[i].set_xlabel()

"""### 4. Feature Engineering
Creating the 'luxury' feature and handling outliers/skewness.
"""

# Creating luxury feature
data['luxury'] = data['airconditioning'] + data['prefarea'] + data['parking']

# Handling Skewness in Price and Area using Log Transformation
data['price'] = np.log1p(data['price'])
data['area'] = np.log1p(data['area'])

data.head()

"""### 5. EDA
Visualizing correlations after cleaning.
"""

plt.figure(figsize=(10, 5))
sns.heatmap(data.corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

"""### 6. Train-Test Split & Scaling
Scaling is essential for Linear Regression.
"""

X = data.drop('price', axis=1)
y = data['price']

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

data

X_train_scaled

X_test_scaled

print("Shape of X_train:", X_train_scaled.shape)

"""### 7. Model Training & Evaluation"""

model = LinearRegression()

model.fit(X_train_scaled, y_train)

# Predictions
y_pred = model.predict(X_test_scaled)

print("R2 Score:", r2_score(y_test, y_pred))
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))

"""RANDOM FOREST"""

rf_model = RandomForestRegressor(n_estimators=100, random_state=42)

rf_model.fit(X_train_scaled, y_train)

rf_pred = rf_model.predict(X_test_scaled)

print("Random Forest Results:")
print("R2 Score:", r2_score(y_test, rf_pred))
print("MSE:", mean_squared_error(y_test, rf_pred))

importances = rf_model.feature_importances_
feature_names = X.columns
feature_importance_df = pd.DataFrame({'Feature': feature_names, 'Importance': importances}).sort_values(by='Importance', ascending=False)

plt.figure(figsize=(10, 6))
sns.barplot(x='Importance', y='Feature', data=feature_importance_df)
plt.title('Feature Importance from Random Forest')
plt.show()